(function (global) {
  "use strict";

  global.ANIME_CALENDAR_TEACH_INDEX = [
    {
      id: "home",
      title: "学习与维护入口",
      path: "index.html",
      section: "首页",
      keywords: ["学习路线", "维护", "项目全景"],
      summary: "从系统课程或真实维护任务进入番剧日历项目。",
    },
    {
      id: "map",
      title: "项目地图与三条数据流",
      path: "map.html",
      section: "项目地图",
      keywords: ["架构", "数据流", "文件地图", "依赖", "data", "lib", "app", "D1"],
      summary: "按八层职责定位代码，并追踪日历、追番和登录的真实数据流。",
    },
    {
      id: "learn-language",
      title: "01 从 C++ / Python 迁移到 JS / TS",
      path: "learn/01-language.html",
      section: "系统课程",
      keywords: ["JavaScript", "TypeScript", "const", "async", "await", "对象", "数组"],
      summary: "把项目常见语法翻译回已有的数据结构、函数和控制流知识。",
    },
    {
      id: "learn-web",
      title: "02 网站如何运行",
      path: "learn/02-web.html",
      section: "系统课程",
      keywords: ["HTTP", "JSON", "Cookie", "localStorage", "401", "浏览器", "Worker"],
      summary: "区分浏览器、Cloudflare Worker、D1 和静态资源的运行边界。",
    },
    {
      id: "learn-react",
      title: "03 React 心智模型",
      path: "learn/03-react.html",
      section: "系统课程",
      keywords: ["React", "UI", "state", "useState", "useEffect", "JSX", "app/page.tsx"],
      summary: "用 UI = f(state) 拆解组件、派生值、effect、事件与大型 Home 页面。",
    },
    {
      id: "learn-architecture",
      title: "04 项目架构与数据流",
      path: "learn/04-architecture.html",
      section: "系统课程",
      keywords: ["data/anime.js", "lib/calendar.js", "app/api", "D1", "架构", "生成文件"],
      summary: "判断静态事实、纯算法、React、API 和个人数据应位于哪一层。",
    },
    {
      id: "learn-calendar",
      title: "05 日历核心算法",
      path: "learn/05-calendar.html",
      section: "系统课程",
      keywords: ["layoutBroadcast", "eventsForWeek", "凌晨", "04:59", "先行", "时间轴", "贪心"],
      summary: "把日期边界、集数展开和时间轴分栏写成输入、输出与不变量。",
    },
    {
      id: "learn-backend",
      title: "06 后端、数据库与安全",
      path: "learn/06-backend.html",
      section: "系统课程",
      keywords: ["API", "D1", "Drizzle", "db.batch", "PBKDF2", "getSessionUser", "Cookie"],
      summary: "理解认证、运行时校验、原子写入、单集键和数据库迁移。",
    },
    {
      id: "learn-tooling",
      title: "07 工具链与运行时",
      path: "learn/07-tooling.html",
      section: "系统课程",
      keywords: ["Node", "npm", "typecheck", "vinext", "Vite", "Cloudflare Worker", "build", "node --test"],
      summary: "沿 Node、vinext、Vite 与 Worker 流水线理解开发、构建和测试。",
    },
    {
      id: "learn-maintenance",
      title: "08 安全维护闭环",
      path: "learn/08-maintenance.html",
      section: "系统课程",
      keywords: ["复现", "回归测试", "最小修复", "验证", "git diff --check", "TDD"],
      summary: "用反例、测试、最小改动和新鲜证据完成一次可审查的修复。",
    },
  ];
})(typeof window === "undefined" ? globalThis : window);
